version: '2.1'
services:
  web:
    build: .
    container_name: proxy_socket1
    hostname: proxy_socket1
    restart: always
    ports:
      - "31337:9000"
    volumes:
      - ./src:/src
    environment:
      PYTHONUNBUFFERED: 1
      PROXY_REMOTE_ADDR: 192.168.138.3
      PROXY_REMOTE_PORT: 32400
